version: '3'
services:
  worker:
    image: opencti/worker:3.1.0
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    deploy: #docker-compose --compatibility up
      mode: replicated
      replicas: 20
    restart: always
    network_mode: "host"