version: '3'
services:
  connector-cyber-threat-coalition:
    image: opencti/connector-cyber-threat-coalition:3.1.0
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_CYBER_THREAT_COALITION_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=CyberThreatCoalition
      - CONNECTOR_SCOPE=indicator,report,identity
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - CYBER_THREAT_COALITION_INTERVAL=10800 # Seconds (3 hours)
      - CYBER_THREAT_COALITION_BASE_URL=https://blacklist.cyberthreatcoalition.org/vetted
    restart: always
    network_mode: "host"