version: '3'
services:
  connector-ipinfo:
    image: opencti/connector-ipinfo:3.1.0
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IPINFO_ID}
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=IpInfo
      - CONNECTOR_SCOPE='ipv4-addr'
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - IPINFO_TOKEN=1f78624ff7a9fe
      - IPINFO_MAX_TLP=TLP:AMBER
    restart: always
    network_mode: "host"